framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 0
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'  # Ensure the synchronous transport is defined

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync  # Route emails to sync for immediate sending
