controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_index:
    path: /back
    controller: App\Controller\UserController::index

app_front:
    path: /
    controller: App\Controller\UserController::front
update_rating:
    path: /update-rating
    controller: App\Controller\ReclamationController::updateRating
    methods: [POST]
